import type { Metadata } from "next"
import { Golos_Text } from "next/font/google"
import { Toaster } from "@/components/ui/sonner"
import "./globals.css"
import { Providers } from "./providers"

const golos = Golos_Text({
	subsets: ["cyrillic", "latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={golos.className}>
				<Providers>{children}</Providers>
				<Toaster />
			</body>
		</html>
	)
}
